version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r day-14/simple-python-app/requirements.txt
  build:
    commands:
      - echo "Running tests..."
      - cd day-14/simple-python-app/
      - echo "Building Docker image..."
      - docker build -t "simple-python-flask-app:latest" .
      - docker save -o simple-python-flask-app.tar "$simple-python-flask-app:latest"
      - aws s3 cp simple-python-flask-app.tar s3://bansal-cicd/simple-python-flask-app.tar
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'
  base-directory: ..day-14/simple-python-app

